source "https://rubygems.org"

ruby '2.6.6'

gem "rake", "~> 13.0"
gem "jekyll", "~> 3.9.2"


gem "sass", "~> 3.7"

gem "liquid", "~> 4.0"

gem "liquid-c", "~> 4.0"

# This is the default theme for new Jekyll sites. You may change this to anything you like.
gem "minima", "~> 2.0"

# If you want to use GitHub Pages, remove the "gem "jekyll"" above and
# uncomment the line below. To upgrade, run `bundle update github-pages`.
# gem "github-pages", group: :jekyll_plugins

# If you have any plugins, put them here!
group :jekyll_plugins do
  gem "uglifier", "~> 4.2"
  gem "sprockets", "~> 3.7"
  gem "jekyll-feed", "~> 0.6"
  gem "jekyll-assets", "> 2.4"
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
# and associated library.
install_if -> { RUBY_PLATFORM =~ %r!mingw|mswin|java! } do
  gem "tzinfo", "~> 1.2"
  gem "tzinfo-data"
end

# Performance-booster for watching directories on Windows
gem "wdm", "~> 0.1.0", :install_if => Gem.win_platform?

# kramdown v2 ships without the gfm parser by default. If you're using
# kramdown v1, comment out this line.
gem "kramdown-parser-gfm"

# Lock `http_parser.rb` gem to `v0.6.x` on JRuby builds since newer versions of the gem
# do not have a Java counterpart.
gem "http_parser.rb", "~> 0.6.0", :platforms => [:jruby]

gem "activesupport", "~> 5.2"
gem "thin", "~> 1.8"

gem "rack", "~> 2.2"

gem "guard-jekyll-plus", "~> 2.0", :git => "https://github.com/imathis/guard-jekyll-plus.git"

gem "guard-livereload", "~> 2.5"

gem "rb-readline", "~> 0.5.5"
